#!/bin/bash
source scripts/env.sh 
NA62AnalysisBuilder.py build TriggerConfig
ls /disk/moose/general/GroupStudies/2020/na62_data_files/* > AllNA62Data.lst
./bin-cc7/myExecutable -l AllNA62Data.lst -o TrigOut.root
rm AllNA62Data.lst
